---
- name: install dependency packages
  yum: state=latest name={{ item }}
  with_items:
    - openssl-devel
    - gcc
    - bzip2
    - libyaml-devel
    - libffi-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel
  tags: 'ruby'

- name: check exists ruby
  become: yes
  become_user: "{{ rbenv.user }}"
  stat: path="{{ rbenv.dest }}/versions/{{ ruby.version }}"
  register: is_ruby_file

- name: "install ruby"
  become: yes
  become_user: "{{ rbenv.user }}"
  shell: "{{ rbenv.dest}}/bin/rbenv install {{ ruby.version }}"
  when: not is_ruby_file.stat.exists
  tags: rbenv

- name: "set using ruby version"
  become: yes
  become_user: "{{ rbenv.user }}"
  shell: "{{ rbenv.dest }}/bin/rbenv global {{ ruby.version }}"
  tags: rbenv
