---
- name: check nginx repo
  stat: path=/etc/pki/rpm-gpg/RPM-GPG-KEY-nginx
  register: is_nginx_rpm_path

- name: enable nginx repos
  yum: state=present name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
  tags: [ 'nginx' ]
  when: not is_nginx_rpm_path.stat.exists

- name: install nginx
  yum: state=latest name=nginx
  tags: [ 'nginx' ]

- name: check nginx service enabled
  stat: path=/etc/systemd/system/multi-user.target.wants/nginx.service
  register: is_nginx_enabled_path

- name: start nginx
  service: name=nginx state=started  enabled=yes
  tags: [ 'nginx' ]
  when: not is_nginx_enabled_path.stat.exists
