---
- hosts: all
  become: yes
  roles:
    - git

- hosts: web
  become: yes
  roles:
    - nginx

- hosts: app
  become: yes
  roles:
    - ruby

- hosts: db
  become: yes
  roles:
    - mysql

- hosts: dev
  become: yes
  roles:
    - node
